/** Carga los contratos de secuencia y de un paso streaming antes de inferir. */
export async function loadInputContract(url='/contracts/gru-ctc-input.schema.json'){return loadSchema(url,validateInputContract);}
/** Carga los contratos reales de frame y entrada TensorFlow.js streaming. */
export async function loadStreamingContracts(frameUrl='/contracts/gru-ctc-streaming-frame.schema.json',inputUrl='/contracts/gru-ctc-streaming-input.schema.json'){return{frameSchema:await loadSchema(frameUrl,validateStreamingFrameSchema),inputSchema:await loadSchema(inputUrl,validateStreamingInputSchema)};}
/** Carga un esquema y aplica su validador estructural. */
async function loadSchema(url,validator){const response=await fetch(url);if(!response.ok)throw new Error(`Contrato GRU/CTC no disponible (${response.status}): ${url}`);const schema=await response.json();validator(schema);return schema;}
/** Valida el contrato de secuencias históricas de 32 frames. */
export function validateInputContract(schema){if(schema?.type!=='array'||schema.minItems!==32||schema.maxItems!==32)throw new Error('Contrato GRU/CTC inválido: la secuencia debe tener exactamente 32 frames.');const frame=schema.items;if(frame?.type!=='array'||frame.minItems!==308||frame.maxItems!==308||frame.items?.type!=='number')throw new Error('Contrato GRU/CTC inválido: cada frame debe tener exactamente 308 números.');return true;}
/** Valida el contrato declarativo de un frame streaming de 308 valores. */
export function validateStreamingFrameSchema(schema){if(schema?.type!=='array'||schema.minItems!==308||schema.maxItems!==308||schema.items?.type!=='number')throw new Error('Contrato streaming de frame inválido: se requieren 308 números.');return true;}
/** Valida el contrato declarativo de frames [1,1,308] y estado [1,128]. */
export function validateStreamingInputSchema(schema){const f=schema?.properties?.frames_308,s=schema?.properties?.estado_gru;if(schema?.type!=='object'||!schema.required?.includes('frames_308')||!schema.required?.includes('estado_gru'))throw new Error('Contrato streaming inválido: faltan entradas requeridas.');if(f?.minItems!==1||f.maxItems!==1||f.items?.minItems!==1||f.items?.maxItems!==1||f.items?.items?.$ref!=='gru-ctc-streaming-frame.schema.json')throw new Error('Contrato streaming inválido: frames_308 no declara [1,1,308].');if(s?.minItems!==1||s.maxItems!==1||s.items?.minItems!==128||s.items?.maxItems!==128)throw new Error('Contrato streaming inválido: estado_gru no declara [1,128].');return true;}
/** Valida datos concretos justo antes de model.execute(). */
export function validateStreamingInput(value){const frames=value?.frames_308,state=value?.estado_gru,frame=frames?.[0]?.[0];if(!Array.isArray(frames)||frames.length!==1||!Array.isArray(frames[0])||frames[0].length!==1||!Array.isArray(frame)||frame.length!==308||frame.some(v=>!Number.isFinite(v)))throw new Error('Entrada streaming inválida: frames_308 debe tener forma [1,1,308].');if(!Array.isArray(state)||state.length!==1||!Array.isArray(state[0])||state[0].length!==128||state[0].some(v=>!Number.isFinite(v)))throw new Error('Entrada streaming inválida: estado_gru debe tener forma [1,128].');return true;}
