/** Pruebas normativas de FASE I: extracción, geometría, tiempo y flujo compartido. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { LiteFrameExtractor, MEDIAPIPE_HANDS_ROOT, MEDIAPIPE_POSE_ROOT } from '../src/vision/LiteFrameExtractor.js';
import { LITE_FEATURE_CONTRACT, LiteTemporalEncoder, regenerateVector139, vectorizeLiteRaw } from '../src/vision/LiteVectorizer139.js';
import { validateSample } from '../src/validacion/validateSample.js';
import { SampleWorkflow } from '../src/validacion/SampleWorkflow.js';
import { ClassCatalog, humanClassId } from '../src/etiquetado/ClassCatalog.js';
import { VideoSegmentProcessor } from '../src/captura/VideoSegmentProcessor.js';

const validClassContract = { validate: async () => ({ valid: true, complete: true, errors: [] }) };
function point(x, y, z = 0, visibility) { return visibility === undefined ? { x, y, z } : { x, y, z, visibility }; }
function hand(offset = 0) { return Array.from({ length: 21 }, (_, index) => point(offset + index / 100, .3 + index / 200, index / 300)); }
function raw({ left = null, right = null, nose = point(.5, .2, .1, .9), leftShoulder = point(.3, .5, 0, .8), rightShoulder = point(.7, .5, 0, .85) } = {}) { return { hands: { left, right }, pose: { nose, leftShoulder, rightShoulder } }; }
function extraction(sourceTimestampMs = 1000, overrides = {}) { return { frameToken: sourceTimestampMs, sourceTimestampMs, raw: raw(overrides) }; }
function sample(frames, classId = 'HOLA', durationMs = frames.at(-1)?.timestampMs ?? 0) { return { featureContract: LITE_FEATURE_CONTRACT, classId, fuente: { tipo: 'camera' }, tiempo: { inicioMs: 0, finMs: durationMs, duracionMs: durationMs, cantidadFrames: frames.length }, frames, capturedAt: '2026-09-22T00:00:00.000Z' }; }

test('01 F139 tiene longitud exacta', () => assert.equal(vectorizeLiteRaw(raw()).length, 139));
test('02 mano izquierda ocupa 0:63', () => { const vector = vectorizeLiteRaw(raw({ left: hand(.1) })); assert.notEqual(vector[0], 0); assert.equal(vector.slice(0, 63).length, 63); });
test('03 mano derecha ocupa 63:126', () => { const vector = vectorizeLiteRaw(raw({ right: hand(.6) })); assert.equal(vector.slice(0, 63).every((value) => value === 0), true); assert.notEqual(vector[63], 0); });
test('04 hombros ocupan 126:132', () => { const vector = vectorizeLiteRaw(raw()); assert.ok(Math.abs(vector[126] + .5) < 1e-12); assert.ok(Math.abs(vector[129] - .5) < 1e-12); assert.deepEqual([vector[127], vector[128], vector[130], vector[131]], [0, 0, 0, 0]); });
test('05 nariz ocupa 132:135', () => { const vector = vectorizeLiteRaw(raw()); assert.ok(Math.abs(vector[132]) < 1e-12); assert.ok(Math.abs(vector[133] + .75) < 1e-12); assert.ok(Math.abs(vector[134] - .25) < 1e-12); });
test('06 máscaras ocupan 135:138', () => assert.deepEqual(vectorizeLiteRaw(raw({ left: hand() })).slice(135, 138), [1, 0, 1]));
test('07 primer delta normalizado es cero', () => assert.equal(new LiteTemporalEncoder().encode(extraction()).vector139[138], 0));
test('08 delta se divide por 1000', () => { const encoder = new LiteTemporalEncoder(); encoder.encode(extraction(1000)); assert.equal(encoder.encode(extraction(1250)).vector139[138], .25); });
test('09 delta se recorta a uno', () => { const encoder = new LiteTemporalEncoder(); encoder.encode(extraction(1000)); assert.equal(encoder.encode(extraction(3000)).vector139[138], 1); });
test('10 hombro ausente descarta frame', () => assert.equal(new LiteTemporalEncoder().encode(extraction(1000, { leftShoulder: null })), null));
test('11 escala degenerada descarta frame', () => assert.equal(vectorizeLiteRaw(raw({ leftShoulder: point(.5, .5), rightShoulder: point(.5, .5) })), null));
test('12 coordenada no finita descarta frame', () => assert.equal(vectorizeLiteRaw(raw({ nose: point(NaN, .2) })), null));
test('13 mano incompleta se considera ausente', async () => { const pose = [point(.5, .2), ...Array(10).fill(null), point(.3, .5), point(.7, .5)]; const extractor = new LiteFrameExtractor({ detect: async () => ({ hands: [hand().slice(0, 20)], handedness: [{ label: 'Right' }], pose }) }); const extracted = await extractor.extract({}, { sourceTimestampMs: 1 }); const frame = new LiteTemporalEncoder().encode(extracted); assert.equal(extracted.raw.hands.left, null); assert.equal(frame.vector139.slice(0, 63).every((value) => value === 0), true); assert.equal(frame.vector139[135], 0); });
test('14 mano ausente produce 63 ceros', () => assert.equal(vectorizeLiteRaw(raw()).slice(0, 63).every((value) => value === 0), true));
test('15 visibility raw se conserva', () => { const frame = new LiteTemporalEncoder().encode(extraction()); assert.equal(frame.raw.pose.nose.visibility, .9); });
test('16 raw no se sustituye por normalizado', () => { const source = raw({ left: hand(.1) }); const snapshot = structuredClone(source); vectorizeLiteRaw(source); assert.deepEqual(source, snapshot); });
test('17 F139 se regenera exactamente desde raw', () => { const frame = new LiteTemporalEncoder().encode(extraction(1000, { left: hand(.1) })); assert.deepEqual(regenerateVector139(frame), frame.vector139); });
test('18 timestamp duplicado no crea frame', () => { const encoder = new LiteTemporalEncoder(); assert.ok(encoder.encode(extraction(1000))); assert.equal(encoder.encode(extraction(1000)), null); });
test('19 timestamp regresivo no crea frame', () => { const encoder = new LiteTemporalEncoder(); encoder.encode(extraction(1000)); assert.equal(encoder.encode(extraction(999)), null); });
test('20 descarte no avanza reloj válido', () => { const encoder = new LiteTemporalEncoder(); encoder.encode(extraction(1000)); encoder.encode(extraction(1200, { nose: null })); assert.equal(encoder.encode(extraction(1500)).vector139[138], .5); });
test('21 extractor asocia Hands y Pose al mismo token', async () => { const extractor = new LiteFrameExtractor({ detect: async () => ({ hands: [hand(.1)], handedness: [{ label: 'Right' }], pose: [point(.5, .2), ...Array(10).fill(null), point(.3, .5), point(.7, .5)] }) }); const result = await extractor.extract({}, { frameToken: 'frame-A', sourceTimestampMs: 50 }); assert.equal(result.frameToken, 'frame-A'); assert.equal(result.sourceTimestampMs, 50); assert.equal(result.raw.hands.left.length, 21); });
test('22 lateralidad física invierte etiqueta selfie de MediaPipe', async () => { const extractor = new LiteFrameExtractor({ detect: async () => ({ hands: [hand(.7), hand(.1)], handedness: [{ label: 'Left' }, { label: 'Right' }], pose: [] }) }); const result = await extractor.extract({}, { sourceTimestampMs: 1 }); assert.equal(result.raw.hands.right[0].x, .7); assert.equal(result.raw.hands.left[0].x, .1); });
test('23 classId humano elimina acentos y espacios', () => assert.equal(humanClassId('¿Cómo estás?'), 'COMO_ESTAS'));
test('24 catálogo preserva ruido_background', async () => { const catalog = new ClassCatalog({ validator: validClassContract }); await catalog.initialize(); assert.equal((await catalog.create({ tipo: 'ruido_background', glosa: 'RUIDO_BACKGROUND' })).classId, 'ruido_background'); });
test('25 muestra Lite válida conserva raw y vector', () => { const frame = new LiteTemporalEncoder().encode(extraction()); assert.deepEqual(validateSample(sample([frame]), { classResolver: () => true }), { valid: true, errors: [] }); });
test('26 flujo rechaza F139 alterado antes de persistir', async () => { const frame = new LiteTemporalEncoder().encode(extraction()); frame.vector139[0] = 999; let writes = 0; const workflow = new SampleWorkflow({ datasetStore: { appendSample: async () => { writes += 1; } }, classProvider: () => ({ classId: 'HOLA' }), classResolver: () => true }); await assert.rejects(() => workflow.save({ classId: 'HOLA', durationMs: 0, frames: [frame] }), /reproducible/); assert.equal(writes, 0); });
test('27 cámara y video comparten una única instancia en main', async () => { const source = await readFile(new URL('../src/main.js', import.meta.url), 'utf8'); assert.equal((source.match(/new LiteFrameExtractor/g) ?? []).length, 1); assert.equal((source.match(/extractor\.extract\(currentVideo, context\)/g) ?? []).length, 3); });
test('28 runtime activo no menciona detectores prohibidos', async () => { const files = ['../src/main.js', '../src/vision/LiteFrameExtractor.js', '../src/vision/LiteVectorizer139.js']; const source = (await Promise.all(files.map((file) => readFile(new URL(file, import.meta.url), 'utf8')))).join('\n'); assert.doesNotMatch(source, /Holistic|FaceMesh|F319|rostro/i); });
test('29 video usa mediaTime como timestamp fuente', async () => { const sequence = [{ mediaTime: .1, presentedFrames: 1 }, { mediaTime: .3, presentedFrames: 2 }, { mediaTime: .6, presentedFrames: 3 }]; let index = 0; const processor = new VideoSegmentProcessor({ video: { pause() {} }, seek: async () => {}, nextFrame: async () => sequence[index++], extractLandmarks: async (_video, context) => extraction(context.sourceTimestampMs) }); const result = await processor.process({ startMs: 0, endMs: 400 }); assert.deepEqual(result.frames.map((frame) => frame.timestampMs), [0, 200]); });
test('30 video reporta saltos presentedFrames sin inventarlos', async () => { const sequence = [{ mediaTime: .1, presentedFrames: 1 }, { mediaTime: .2, presentedFrames: 4 }, { mediaTime: .5, presentedFrames: 5 }]; let index = 0; const processor = new VideoSegmentProcessor({ video: { pause() {} }, seek: async () => {}, nextFrame: async () => sequence[index++], extractLandmarks: async (_video, context) => extraction(context.sourceTimestampMs) }); const result = await processor.process({ startMs: 0, endMs: 300 }); assert.equal(result.diagnostics[0].omittedFrames, 2); assert.equal(result.frames.length, 2); });
test('31 extractor no reutiliza manos de un frame anterior', async () => { let call = 0; const pose = [point(.5, .2), ...Array(10).fill(null), point(.3, .5), point(.7, .5)]; const extractor = new LiteFrameExtractor({ detect: async () => call++ === 0 ? { hands: [hand()], handedness: [{ label: 'Right' }], pose } : { hands: [], handedness: [], pose } }); const first = await extractor.extract({}, { sourceTimestampMs: 1 }); const second = await extractor.extract({}, { sourceTimestampMs: 2 }); assert.equal(first.raw.hands.left.length, 21); assert.equal(second.raw.hands.left, null); });
test('32 Hands y Pose se crean e inicializan una sola vez', async () => { const events = []; const extractor = new LiteFrameExtractor({ handsFactory: fakeSolution('hands', events), poseFactory: fakeSolution('pose', events) }); await extractor.extract({}, { sourceTimestampMs: 1 }); await extractor.extract({}, { sourceTimestampMs: 2 }); assert.equal(events.filter((item) => item === 'hands:construct').length, 1); assert.equal(events.filter((item) => item === 'pose:construct').length, 1); assert.equal(events.filter((item) => item === 'hands:initialize').length, 1); assert.equal(events.filter((item) => item === 'pose:initialize').length, 1); });
test('33 inicialización termina Hands antes de construir Pose', async () => { const events = []; await new LiteFrameExtractor({ handsFactory: fakeSolution('hands', events), poseFactory: fakeSolution('pose', events) }).extract({}, { sourceTimestampMs: 1 }); assert.ok(events.indexOf('hands:initialize:end') < events.indexOf('pose:construct')); assert.ok(events.indexOf('pose:initialize:end') < events.indexOf('hands:send')); });
test('34 arranque no contiene Promise.all', async () => { const source = await readFile(new URL('../src/vision/LiteFrameExtractor.js', import.meta.url), 'utf8'); const initialization = source.slice(source.indexOf('async #initialize'), source.indexOf('export function buildRawLite')); assert.doesNotMatch(initialization, /Promise\.all/); });
test('35 locateFile mantiene raíces y versiones separadas', async () => { const events = []; await new LiteFrameExtractor({ handsFactory: fakeSolution('hands', events), poseFactory: fakeSolution('pose', events) }).extract({}, { sourceTimestampMs: 1 }); assert.ok(events.includes(`hands:asset:${MEDIAPIPE_HANDS_ROOT}/runtime.wasm`)); assert.ok(events.includes(`pose:asset:${MEDIAPIPE_POSE_ROOT}/runtime.wasm`)); });
test('36 fallo de Hands impide crear Pose', async () => { const events = []; const extractor = new LiteFrameExtractor({ handsFactory: fakeSolution('hands', events, { initializeError: 'hands abort' }), poseFactory: fakeSolution('pose', events) }); await assert.rejects(() => extractor.extract({}, { sourceTimestampMs: 1 }), /MediaPipe Hands: hands abort/); assert.equal(events.includes('pose:construct'), false); });
test('37 fallo de Pose produce error explícito', async () => { const events = []; const extractor = new LiteFrameExtractor({ handsFactory: fakeSolution('hands', events), poseFactory: fakeSolution('pose', events, { initializeError: 'pose abort' }) }); await assert.rejects(() => extractor.extract({}, { sourceTimestampMs: 1 }), /MediaPipe Pose: pose abort/); });
test('38 index no carga soluciones MediaPipe legacy ni duplicadas', async () => { const html = await readFile(new URL('../index.html', import.meta.url), 'utf8'); assert.doesNotMatch(html, /mediapipe|holistic|face_mesh|hands\.js|pose\.js/i); });

/** Solution mínima que permite observar orden, assets y número de inicializaciones. */
function fakeSolution(name, events, { initializeError = null } = {}) {
  return class {
    constructor({ locateFile }) { events.push(`${name}:construct`); events.push(`${name}:asset:${locateFile('runtime.wasm')}`); }
    setOptions() { events.push(`${name}:options`); }
    onResults(callback) { this.callback = callback; }
    async initialize() { events.push(`${name}:initialize`); if (initializeError) throw new Error(initializeError); events.push(`${name}:initialize:end`); }
    async send() { events.push(`${name}:send`); this.callback(name === 'hands' ? { multiHandLandmarks: [], multiHandedness: [] } : { poseLandmarks: [] }); }
  };
}
