import test from 'node:test';
import assert from 'node:assert/strict';
import { validateInputContract, validateStreamingFrameSchema, validateStreamingInputSchema, validateStreamingInput } from '../src/reconocimiento/contractValidator.js';
test('acepta el contrato temporal [32,308]',()=>assert.equal(validateInputContract({type:'array',minItems:32,maxItems:32,items:{type:'array',minItems:308,maxItems:308,items:{type:'number'}}}),true));
test('rechaza contrato sin dimensiones exactas',()=>assert.throws(()=>validateInputContract({type:'array',minItems:1,maxItems:32,items:{type:'array',minItems:308,maxItems:308,items:{type:'number'}}}),/32 frames/));
test('valida frame streaming de 308 valores',()=>assert.equal(validateStreamingFrameSchema({type:'array',minItems:308,maxItems:308,items:{type:'number'}}),true));
test('rechaza frame streaming inválido',()=>assert.throws(()=>validateStreamingInput({frames_308:[ [Array(307).fill(0)] ],estado_gru:[Array(128).fill(0)]}),/frames_308/));
test('valida forma declarada streaming',()=>assert.equal(validateStreamingInputSchema({type:'object',required:['frames_308','estado_gru'],properties:{frames_308:{minItems:1,maxItems:1,items:{minItems:1,maxItems:1,items:{$ref:'gru-ctc-streaming-frame.schema.json'}}},estado_gru:{minItems:1,maxItems:1,items:{minItems:128,maxItems:128}}}}),true));
test('valida entrada concreta [1,1,308] y [1,128]',()=>assert.equal(validateStreamingInput({frames_308:[[Array(308).fill(0)]],estado_gru:[Array(128).fill(0)]}),true));
test('rechaza secuencia [32,308] como entrada directa',()=>assert.throws(()=>validateStreamingInput({frames_308:[Array.from({length:32},()=>Array(308).fill(0))],estado_gru:[Array(128).fill(0)]}),/frames_308/));
