import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { LiteModelRuntime } from '../src/modelo/LiteModelRuntime.js';
const metadata={featureContract:'AULASENAS2_LITE_F139_V1',input:{shape:[null,20,139]},output:{shape:[null,12]},gru:{stateful:false}};
const classMapping={class_to_index:{ruido_background:0,BIEN:1,BUENAS_NOCHES:2,BUENAS_TARDES:3,BUENOS_DIAS:4,COMO_ESTAS:5,CUAL_ES_TU_NOMBRE:6,GRACIAS:7,HASTA_MANANA:8,LO_SIENTO:9,MI_NOMBRE:10,PERMISO:11}};
const rows=()=>Array.from({length:20},()=>new Float32Array(139));
function fixture(){let disposed=0; const tf={tensor(values,shape,dtype){assert.equal(values.length,20*139); assert.deepEqual(shape,[1,20,139]); assert.equal(dtype,'float32'); return {dispose(){disposed+=1;}};},async loadLayersModel(){return {inputs:[{shape:[null,20,139]}],predict(){return {shape:[1,12],data:async()=>Float32Array.from([.9,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01,.0]),dispose(){disposed+=1;}};}}}}; const fetchImpl=async(url)=>({ok:true,json:async()=>url.endsWith('model_metadata.json')?metadata:classMapping}); return {runtime:new LiteModelRuntime({tfRuntime:tf,fetchImpl}),tf,getDisposed:()=>disposed};}
test('runtime carga LayersModel, valida mapping y no mantiene estado GRU', async()=>{const {runtime,getDisposed}=fixture(); await runtime.load(); assert.equal(runtime.state,'ready'); const result=await runtime.predict(rows()); const repeat=await runtime.predict(rows()); assert.deepEqual(repeat.probabilities,result.probabilities); assert.equal(result.index,0); assert.equal(result.classId,'ruido_background'); assert.equal(result.background,true); assert.equal(getDisposed(),4);});
test('runtime no infiere antes de una ventana [20,139] válida', async()=>{const {runtime}=fixture(); await runtime.load(); await assert.rejects(()=>runtime.predict(rows().slice(0,19)),/20,139/);});
test('fetch predeterminado conserva el contexto global requerido por el navegador', async()=>{const previousFetch=globalThis.fetch; const requested=[]; globalThis.fetch=async function(url){assert.equal(this,globalThis); requested.push(url); return {ok:true,json:async()=>url.endsWith('model_metadata.json')?metadata:classMapping};}; try {const {tf}=fixture(); const runtime=new LiteModelRuntime({tfRuntime:tf}); await runtime.load(); assert.equal(runtime.state,'ready'); assert.equal(requested.length,2);} finally {globalThis.fetch=previousFetch;}});
test('fetch inyectado sigue funcionando sin depender del fetch global', async()=>{const previousFetch=globalThis.fetch; globalThis.fetch=()=>{throw new Error('No debe usarse el fetch global.');}; try {const {runtime}=fixture(); await runtime.load(); assert.equal(runtime.state,'ready');} finally {globalThis.fetch=previousFetch;}});
test('main registra el error rechazado por la carga del modelo', async()=>{const source=await readFile(new URL('../src/main.js',import.meta.url),'utf8'); assert.doesNotMatch(source,/modelRuntime\.load\(\)\.catch\(\(\)\s*=>\s*\{\s*\}\)/); assert.match(source,/modelRuntime\.load\(\)\.catch\(\(error\)\s*=>\s*console\.error/);});
