/** Presenta estados y resultados del flujo real; no ejecuta reconocimiento. */
export class UserInterface{constructor(){this.currentText='';this.cameraStatus=document.querySelector('#camera-status');this.video=document.querySelector('#camera');this.placeholder=document.querySelector('#camera-placeholder');this.badge=document.querySelector('#recording-badge');this.transcript=document.querySelector('#transcript');this.interpretation=document.querySelector('#interpretation');this.speak=document.querySelector('#speak-button');this.detail=document.querySelector('#recognition-detail');}
/** Conecta controles de cámara, limpieza, preferencias y voz. */
bind({camera,speech,preferences}){document.querySelector('#camera-toggle').onclick=async e=>{e.currentTarget.disabled=true;try{if(camera.active){camera.stop();e.currentTarget.textContent='Iniciar traducción';}else{await camera.start();e.currentTarget.textContent='Detener cámara';}}catch{this.setCameraStatus('error');}finally{e.currentTarget.disabled=false;}};document.querySelector('#clear-button').onclick=()=>this.setText('');this.speak.onclick=()=>speech.speak(this.currentText);document.querySelector('#settings-button').onclick=()=>document.querySelector('#settings-dialog').showModal();document.querySelector('#voice-language').value=preferences.get('voiceLanguage');document.querySelector('#auto-speak').checked=preferences.get('autoSpeak');document.querySelector('#settings-dialog form').onsubmit=()=>preferences.set({voiceLanguage:document.querySelector('#voice-language').value,autoSpeak:document.querySelector('#auto-speak').checked});}
/** Actualiza texto acumulado y estado vacío. */
setText(text){this.currentText=text.trim();this.transcript.textContent=this.currentText||'Sin texto acumulado';this.transcript.dataset.empty=String(!this.currentText);this.interpretation.textContent=this.currentText?this.interpretation.textContent:'Sin texto interpretado';this.interpretation.dataset.empty=String(!this.currentText);this.speak.disabled=!this.currentText;}
/** Refleja permisos, errores y estado del stream. */
setCameraStatus(status){const labels={active:'Estado: cámara activa',stopped:'Estado: cámara detenida',error:'Estado: no se pudo acceder a la cámara'};this.cameraStatus.textContent=labels[status]||labels.error;this.video.classList.toggle('visible',status==='active');this.placeholder.hidden=status==='active';this.badge.hidden=status!=='active';}
/** Refleja el estado del modelo y su contrato. */
setModelStatus(status){const available=status?.disponible===true||status==='ready';document.querySelector('#model-status').textContent=available?'Modelo cargado':status?.error?'Error del modelo':'Modelo no disponible';document.querySelector('#translation-status').textContent=available?'Listo':'Pendiente';}
setRecognitionStatus(status){this.detail.textContent=status||'Sin inferencia activa';}
/** Muestra el resultado de cargar el contrato externo sin ocultar errores reales. */
setContractStatus(status){if(this.detail)this.detail.textContent=status||'Contrato no disponible';}
/** Acumula solo predicciones emitidas por GRU-CTC real. */
addRecognition(result,translator,speech,preferences){if(!result?.label)return;this.setText(`${this.currentText} ${result.label}`);const interpreted=translator.interpret(this.currentText);this.interpretation.textContent=interpreted;this.interpretation.dataset.empty='false';this.detail.textContent=`${result.label} (${Number(result.confianza*100).toFixed(1)}%)`;if(preferences.get('autoSpeak'))speech.speak(interpreted);}}
