export class UserInterface {
  constructor() { this.currentText = ''; this.cameraStatus = document.querySelector('#camera-status'); this.video = document.querySelector('#camera'); this.placeholder = document.querySelector('#camera-placeholder'); this.badge = document.querySelector('#recording-badge'); this.transcript = document.querySelector('#transcript'); this.interpretation = document.querySelector('#interpretation'); this.speak = document.querySelector('#speak-button'); this.detail = document.querySelector('#recognition-detail'); }
  bind({ camera, recognizer, translator, speech, preferences }) { document.querySelector('#camera-toggle').onclick = async (event) => { event.currentTarget.disabled = true; try { if (camera.active) { camera.stop(); event.currentTarget.textContent = 'Iniciar cámara'; } else { await camera.start(); event.currentTarget.textContent = 'Detener cámara'; } } catch { this.setCameraStatus('error'); } finally { event.currentTarget.disabled = false; } }; document.querySelector('#clear-button').onclick = () => this.setText(''); this.speak.onclick = () => speech.speak(this.currentText); document.querySelector('#settings-button').onclick = () => document.querySelector('#settings-dialog').showModal(); document.querySelector('#voice-language').value = preferences.get('voiceLanguage'); document.querySelector('#auto-speak').checked = preferences.get('autoSpeak'); document.querySelector('#settings-dialog form').onsubmit = () => preferences.set({ voiceLanguage: document.querySelector('#voice-language').value, autoSpeak: document.querySelector('#auto-speak').checked }); recognizer.onSign = (sign) => { if (!sign || typeof sign !== 'string') return; this.setText(`${this.currentText} ${sign}`); const translated = translator.interpret(this.currentText); this.interpretation.textContent = translated || 'La interpretación aparecerá cuando haya texto reconocido.'; if (translated && preferences.get('autoSpeak')) speech.speak(translated); }; recognizer.load(); }
  setText(text) { this.currentText = text.trim(); this.transcript.textContent = this.currentText || 'Sin texto acumulado'; this.transcript.dataset.empty = String(!this.currentText); this.interpretation.dataset.empty = String(!this.currentText); this.interpretation.textContent = this.currentText ? this.interpretation.textContent : 'Sin texto interpretado'; this.speak.disabled = !this.currentText; }
  setCameraStatus(status) { const labels = { active: 'Cámara activa', stopped: 'Cámara detenida', error: 'No se pudo acceder a la cámara' }; this.cameraStatus.innerHTML = `<i></i> ${labels[status] || labels.stopped}`; this.cameraStatus.className = `status ${status}`; this.video.classList.toggle('visible', status === 'active'); this.placeholder.hidden = status === 'active'; this.badge.hidden = status !== 'active'; document.querySelector('#recognition-status').textContent = status === 'active' ? 'Reconocimiento listo' : 'Reconocimiento inactivo'; }
  setModelStatus(status) { document.querySelector('#model-status').textContent = status === 'ready' ? 'Modelo cargado' : status === 'error' ? 'Error del modelo' : 'Modelo no disponible'; document.querySelector('#translation-status').textContent = status === 'ready' ? 'Listo' : 'Pendiente'; }
  setVisionStatus(status) { document.querySelector('#recognition-status').textContent = status === 'ready' ? 'Visión lista' : 'MediaPipe no disponible'; }
  setRecognitionStatus(status) { if (this.detail) this.detail.textContent = status === 'buffering' ? 'Reuniendo 32 frames' : status === 'inferred' ? 'Inferencia realizada' : status === 'missing' ? 'Modelo no disponible' : status === 'error' ? 'Error de inferencia' : status; }
  addRecognition({ label, confidence }) { this.setText(`${this.currentText} ${label}`); this.detail.textContent = `${label} (${(confidence * 100).toFixed(1)}%)`; }
}
